### ISSUE TITLE
Periodic oscillation in CO2 measurments with two sensors

### ISSUE THREAD

**Issue by kavmar** [LaskaKit/SCD41-CO2-Sensor#1]
Hi

I bought two of the SCD41 sensors and have them connected both on the same Arduino Uno board. If **only one** of any of the two sensors is connected to either of the two input connectors, the measurements is OK. If **both of the sensors** are connected I observe significant oscillations in CO2 measurements every about 7 minutes. They last about 4 minutes. Temperature and humidity measurements are OK. I do not suspect power supply be an issue, because I assume all the measurements would be affected.

Any idea would be highly appreciated.

![image](https://github.com/user-attachments/assets/fdfebd63-01ca-47b3-922b-c6c4949cfaf4)

**Comment by Konstantin-G** [comment]
There can not be 2 sensors on one I2C bus. Sensor has fixed I2C address.
